### ISSUE TITLE
actregiondefine.chm is not completed.

### ISSUE THREAD

**Issue by MilesYyh** [RagnarB83/chemshell-QMMM-protein-setup#6]
Hi! Sorry to bother again.

I found some mistakes in the actregiondefine.chm code:
  1.“set frag $argv” need to modified to "set frag system.c"
  2. "select.tcl" is not provided here
  3. when runing the "chemsh actregiondefine.chm", it didn't output the act file. So i guess the code of  actregiondefine.chm is not complete.

**Comment by RagnarB83** [comment]
1. "$argv" comes from the input argument. You should use the script like this: chemshell.sh actregiondefine.chm file.c . Then the filename becomes the $argv variable.

2. I will try to dig up select.tcl

But I don't really recommend trying to use any of these scripts since ASH is more convenient.

**Comment by MilesYyh** [comment]
1. Actually, i had tried to run the "chemsh actregiondefine_bk.chm  system.c" before. It didn't work. So i  do “set frag $argv” need to modified to "set frag system.c"
![5](https://github.com/RagnarB83/chemshell-QMMM-protein-setup/assets/87625921/b9259130-7c36-419d-8259-efba99fb8cd9)
2. The reason why i use these scripts instead of ASH is that I am reading your paprer about "QM/MM Study of the Nitrogenase MoFe Protein Resting State: Broken-Symmetry States, Protonation States, and QM Region Convergence in the FeMoco Active Site ". I want to learn some details from these scripts instead of using ASH directly, althought ASH is really convenient.
3. Hope you find the select.tcl! 

I indeed thank for your response! By the way, is the ASH had puplished paper for which i can cite in my work. sooner ?
Best regards.

**Comment by RagnarB83** [comment]
Mmm, I think we were using a wrapper shell script around chemsh that allows multiple command-line arguments. Can't remember the details and don't have much desire to touch Tcl or Chemshell again.

Found the select.tcl file, has been added to the repository.

It's easy to mimic everything in that paper with ASH. 

ASH paper is being written.

**Comment by MilesYyh** [comment]
Fine! Thank for your response aganin. 

I think the same as you. 
And I had added  our group  QM tool (paper is being written,too ) interface to the ASH in our local computers. So i will pay attention to the ASH paper.

Best withes.
